spring.application.name=billing-software

server.port=8080


#DB CONFIGURATIONS FOR h2 DB
spring.datasource.url=jdbc:h2:file:./data/billingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=db-admin
spring.datasource.password=adminuser
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#LOAD DB SCRIPT ALWAYS
#spring.sql.init.mode=always

#DONT CREATE TABLES USING JPA SINCE WE ARE USING SQL SCRIPTS
spring.jpa.hibernate.ddl-auto = none


#DATABASE MIGRATION TOOL
spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics






